#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

##################################################################################
############           CENTRIFUGAL PUMP TUTORIAL BY CFD-TRAINING      ############
############                      www.cfd-training.com                ############
##################################################################################

echo "----------> Create .foam file for paraview"
touch pump.foam
echo "----------> Restore 0 Dir"
rm -rf 0 
cp -R 0.orig 0
echo "----------> Decompose case on 6 cores"
decomposePar -force > log.decomposePar
echo "----------> RenumberMesh for parallelisation optimization "
mpirun -np 6 renumberMesh -parallel -overwrite > log.renumberMesh
(echo "----------> Run de solver pimpleFoam on 6 cores the :" && date)
mpirun -np 6 pimpleFoam -parallel > log.pimpleFoam
(echo "----------> End of solver calculation the :" && date)
#------------------------------------------------------------------------------
